import { heading, card, browser, key, cursor, logo } from './helpers.mjs';

export default [
  {
    id: 's10', theme: 'light',
    html: `<div class="enter">${heading('Keep the useful words', 'Read it. Use it. Find it again.')}</div>
      <div class="use-stage">
        <div class="copy-source">${card('Wir melden uns morgen mit den nächsten Schritten.', 'German')}${cursor}<span class="copied pill"><span class="tick">✓</span> Copied</span><p class="small-label">Copy from the result card</p></div>
        <div class="latest"><div class="latest-header"><img src="assets/icon-master.png" alt="" /><div><strong>AI Translator</strong><p>Gemini translation</p></div><span class="ready">Ready</span></div><div class="latest-metrics"><span>Keyboard trigger</span><strong>Control</strong></div><div class="latest-metrics"><span>Active translations</span><strong>0</strong></div><div class="latest-body"><p class="latest-label">LATEST THIS SESSION</p><p class="latest-text">Wir melden uns morgen mit den nächsten Schritten.</p><p class="latest-meta">German · Latest translation</p><span class="button">Copy</span></div><div class="latest-settings">Settings</div></div>
        <div class="latest-caption"><span class="dot"></span> Your latest result, in the toolbar popup</div>
      </div><p class="corner-note">Latest result stays for the current browser session.</p>`,
    css: `#s10 .stage{justify-content:flex-start;padding-top:154px}#s10 h1{font-size:88px}#s10 .use-stage{height:660px;flex-shrink:0;position:relative;margin-top:14px}#s10 .copy-source{position:absolute;left:15px;top:30px}#s10 .copy-source .translation-card{width:745px}#s10 .copy-source .translated{font-size:42px;padding:32px 30px 26px}#s10 .copy-source .small-label{margin-top:26px}#s10 .cursor{left:640px;top:220px}#s10 .copied{position:absolute;left:470px;top:340px;box-shadow:0 10px 28px #0001}#s10 .latest{position:absolute;right:35px;top:-8px;width:580px;padding:26px;background:#f5f5f7;border:2px solid #dddde3;border-radius:24px;box-shadow:0 28px 70px #17121f22}#s10 .latest-header{display:flex;align-items:center;gap:16px;margin-bottom:24px}#s10 .latest-header img{width:54px;height:54px}#s10 .latest-header strong{font-size:28px}#s10 .latest-header p{font-size:22px;color:#6e6e73;margin-top:3px}#s10 .ready{margin-left:auto;padding:8px 13px;background:#e8e8ed;border-radius:99px;color:#176b2c;font-size:19px;font-weight:650}#s10 .latest-metrics{display:flex;justify-content:space-between;padding:14px 18px;font-size:23px;background:white;border:1px solid #dddde3}#s10 .latest-metrics:first-of-type{border-radius:13px 13px 0 0}#s10 .latest-metrics span{color:#6e6e73}#s10 .latest-body{padding:22px 20px;margin-top:18px;background:white;border:1px solid #dddde3;border-radius:15px}#s10 .latest-label{font-size:19px;letter-spacing:1px;color:#6e6e73}#s10 .latest-text{font-size:31px;line-height:1.35;margin-top:12px}#s10 .latest-meta{font-size:20px;margin:14px 0;color:#6e6e73}#s10 .latest-body .button{font-size:21px;padding:9px 17px}#s10 .latest-settings{margin-top:18px;text-align:center;padding:12px;background:#0068c9;color:#fff;border-radius:11px;font-size:24px;font-weight:600}#s10 .latest-caption{position:absolute;right:40px;top:615px;font-size:25px;color:#6e6e73;display:flex;gap:13px;align-items:center}#s10 .dot{width:10px;height:10px;border-radius:50%;background:#0068c9}`,
    motion: `tl.fromTo(q('.copy-source'),{opacity:0,x:-60},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+.5);tl.fromTo(q('.cursor'),{opacity:0,x:70,y:50},{opacity:1,x:0,y:0,duration:.7,ease:'power2.out'},s+1.7);tl.to(q('.copy-source .copy-button'),{scale:.94,duration:.12,yoyo:true,repeat:1},s+2.5);tl.fromTo(q('.copied'),{opacity:0,y:14,scale:.94},{opacity:1,y:0,scale:1,duration:.35,ease:'power2.out'},s+2.75);tl.to(q('.cursor'),{opacity:0,duration:.25},s+3.1);tl.fromTo(q('.latest'),{opacity:0,y:50,scale:.96},{opacity:1,y:0,scale:1,duration:.75,ease:'power3.out'},s+d*.45);tl.fromTo(q('.latest-caption'),{opacity:0,y:12},{opacity:1,y:0,duration:.45},s+d*.5);`,
  },
  {
    id: 's11', theme: 'light',
    html: `<div class="enter">${heading('Flexible by design', 'Make it yours.')}</div><div class="preferences-grid">
      <div class="preference-panel key-panel"><p class="panel-label">Keyboard trigger</p>${key('Shift')}<span class="key-note">Choose a single key in Settings</span></div>
      <div class="preference-panel menu-panel"><p class="panel-label">Or right-click your selection</p><div class="context-menu"><div>Copy</div><div>Search Google</div><div class="menu-translation"><img src="assets/icon-master.png" alt="" /> Translate Selected Text</div></div>${cursor}</div>
      <div class="preference-panel model-panel"><div><p class="setup-label">Default language</p><div class="setup-field">German <span>⌄</span></div></div><div><p class="setup-label">Model</p><div class="setup-field">Gemini 3.5 Flash-Lite <span>⌄</span></div></div><p class="small-label">Your language. Your model. Your choice.</p></div>
      </div>`,
    css: `#s11 .stage{justify-content:flex-start;padding-top:155px}#s11 .preferences-grid{display:grid;grid-template-columns:420px 600px 1fr;gap:28px;margin-top:6px}#s11 .preference-panel{border:2px solid #dedee5;border-radius:24px;background:#fff;padding:32px;height:478px;position:relative}#s11 .panel-label{font-size:25px;font-weight:650;margin-bottom:32px}#s11 .keycap{width:250px;height:216px;margin:0 auto}#s11 .keycap span{font-size:62px}#s11 .keycap small{visibility:hidden}#s11 .key-note{display:block;font-size:24px;line-height:1.3;color:#6e6e73;margin-top:28px;text-align:center}#s11 .context-menu{padding:12px;background:#f6f6f8;border:2px solid #d1d1d8;border-radius:17px;box-shadow:0 20px 40px #17121f22;margin-top:51px}#s11 .context-menu div{height:61px;padding:15px 14px;font-size:25px;border-radius:9px;display:flex;align-items:center;gap:12px}#s11 .context-menu .menu-translation{background:#0068c9;color:#fff}#s11 .menu-translation img{width:29px;height:29px}#s11 .cursor{left:418px;top:297px}#s11 .model-panel{display:flex;flex-direction:column;justify-content:center;gap:34px}#s11 .setup-label{font-size:25px}#s11 .setup-field{font-size:26px;display:flex;justify-content:space-between;padding:18px}#s11 .setup-field span{margin-left:12px}#s11 .model-panel .small-label{font-size:24px}`,
    motion: `tl.fromTo(q('.key-panel'),{opacity:0,y:35},{opacity:1,y:0,duration:.6,ease:'power3.out'},s+.65);tl.fromTo(q('.keycap'),{rotation:-6,scale:.94},{rotation:0,scale:1,duration:.65,ease:'power3.out'},s+.9);tl.fromTo(q('.menu-panel'),{opacity:0,y:35},{opacity:1,y:0,duration:.6,ease:'power3.out'},s+d*.28);tl.fromTo(q('.cursor'),{opacity:0,x:35,y:40},{opacity:1,x:0,y:0,duration:.5},s+d*.37);tl.fromTo(q('.menu-translation'),{backgroundColor:'#f6f6f8',color:'#1d1d1f'},{backgroundColor:'#0068c9',color:'#fff',duration:.25},s+d*.42);tl.fromTo(q('.model-panel'),{opacity:0,y:35},{opacity:1,y:0,duration:.6,ease:'power3.out'},s+d*.51);`,
  },
  {
    id: 's12', theme: 'dark',
    html: `<div class="enter">${heading('A simpler translation tool', 'Free. Open source.')}</div><div class="trust-stage"><div class="trust-benefits"><div class="trust-row ads"><span class="check-ring">✓</span><strong>No ads</strong></div><div class="trust-row analytics"><span class="check-ring">✓</span><strong>No analytics</strong></div></div><div class="sharing"><div class="source-selection"><p class="small-label">The text you select</p><p><span class="selected">The next useful idea.</span></p></div><div class="sharing-route"><span class="route-line"></span><span class="route-packet"></span></div><div class="google-destination"><span class="google-letter">AI</span><strong>Google Gemini</strong><p>When you request a translation</p></div></div></div><p class="corner-note">Free extension. Google API charges may apply.</p>`,
    css: `#s12 .stage{justify-content:flex-start;padding-top:169px}#s12 h1{font-size:120px;letter-spacing:-5px}#s12 .trust-stage{display:grid;grid-template-columns:490px 1fr;align-items:center;gap:100px;margin-top:48px}#s12 .trust-benefits{display:flex;flex-direction:column;gap:42px}#s12 .trust-row{display:flex;align-items:center;gap:23px;font-size:49px;letter-spacing:-1.3px}#s12 .check-ring{display:flex;align-items:center;justify-content:center;width:62px;height:62px;border:2px solid #736284;border-radius:50%;color:#cfbcdf;font-size:36px}#s12 .sharing{border:2px solid #62536f;border-radius:26px;padding:37px 39px 31px;background:#241b2f;position:relative}#s12 .source-selection .small-label{font-size:25px;color:#c5bbd0;margin-bottom:20px}#s12 .source-selection>p:last-child{font-size:41px;font-weight:550;line-height:1.3}#s12 .selected{background:#dcecff;color:#16395f;padding:6px 9px;border-radius:5px}#s12 .sharing-route{height:76px;position:relative;margin-left:15px}#s12 .route-line{height:47px;width:2px;background:#796a88;position:absolute;left:0;top:15px}#s12 .route-packet{width:9px;height:12px;background:#b48cea;border-radius:5px;position:absolute;left:-3px;top:14px}#s12 .route-arrow{position:absolute;left:19px;top:34px;font-size:40px;line-height:1;rotate:90deg;color:#a191b0}#s12 .google-destination{display:grid;grid-template-columns:74px 1fr;column-gap:21px;align-items:center}#s12 .google-letter{width:74px;height:74px;border:2px solid #74617f;border-radius:19px;display:flex;align-items:center;justify-content:center;font-size:42px;font-weight:650;grid-row:span 2;background:#362541}#s12 .google-destination strong{font-size:34px}#s12 .google-destination p{font-size:24px;color:#c5bbd0;margin-top:6px}`,
    motion: `tl.fromTo(q('.ads'),{opacity:0,x:-30},{opacity:1,x:0,duration:.55,ease:'power3.out'},s+.8);tl.fromTo(q('.analytics'),{opacity:0,x:-30},{opacity:1,x:0,duration:.55,ease:'power3.out'},s+1.5);tl.fromTo(q('.sharing'),{opacity:0,y:35},{opacity:1,y:0,duration:.7,ease:'power3.out'},s+d*.4);tl.fromTo(q('.selected'),{backgroundColor:'#241b2f',color:'#f5f5f7'},{backgroundColor:'#dcecff',color:'#16395f',duration:.45},s+d*.48);tl.fromTo(q('.route-packet'),{opacity:0,y:0},{opacity:1,y:42,duration:.7,ease:'power1.inOut'},s+d*.59);tl.fromTo(q('.google-destination'),{opacity:0,y:12},{opacity:1,y:0,duration:.45},s+d*.6);`,
  },
  {
    id: 's13', theme: 'dark',
    html: `<p class="eyebrow enter">Stay with the idea</p><div class="flow-type"><div class="flow-line less-copy">Less copying.<span class="flow-strike"></span></div><div class="flow-line less-switch">Less switching.<span class="flow-strike"></span></div><div class="flow-line more-meaning">More understanding.</div></div><div class="flow-payoff"><span class="flow-dot"></span><p>Keep your place. Keep your flow.</p></div>`,
    css: `#s13 .stage{padding-top:145px;padding-bottom:118px;justify-content:center}#s13 .eyebrow{margin-bottom:32px}#s13 .flow-type{display:flex;flex-direction:column;gap:24px}#s13 .flow-line{font-size:115px;line-height:1.05;font-weight:700;letter-spacing:-5px;position:relative;width:max-content}#s13 .less-copy,#s13 .less-switch{color:#a499ae}#s13 .flow-strike{position:absolute;left:0;right:0;height:4px;top:57%;background:#d2b4e9;transform-origin:left}#s13 .more-meaning{color:#f5f5f7}#s13 .flow-payoff{display:flex;align-items:center;gap:20px;margin-top:62px;color:#d1c4dc;font-size:36px}#s13 .flow-dot{height:13px;width:13px;border-radius:50%;background:#a5cdff}`,
    motion: `tl.fromTo(q('.less-copy'),{opacity:0,x:-80},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+.35);tl.fromTo(q('.less-copy .flow-strike'),{scaleX:0},{scaleX:1,duration:.4,ease:'power2.inOut'},s+1.05);tl.fromTo(q('.less-switch'),{opacity:0,x:-80},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+1.2);tl.fromTo(q('.less-switch .flow-strike'),{scaleX:0},{scaleX:1,duration:.4,ease:'power2.inOut'},s+1.9);tl.fromTo(q('.more-meaning'),{opacity:0,y:45},{opacity:1,y:0,duration:.7,ease:'power3.out'},s+2.2);tl.fromTo(q('.flow-payoff'),{opacity:0,y:18},{opacity:1,y:0,duration:.55},s+d*.44);tl.fromTo(q('.flow-type'),{scale:1},{scale:1.025,duration:d*.48,ease:'none',transformOrigin:'left center'},s+d*.45);`,
  },
  {
    id: 's14', theme: 'light',
    html: `<div class="enter">${heading('A quick setup · 1 of 3', 'Install once.')}</div>${browser(`<div class="store-nav"><strong>chrome web store</strong><span>Extensions</span></div><div class="store-listing"><div class="store-product">${logo}<div><h2>AI Translator</h2><p>Translate selected text with AI.</p><span class="store-category">Productivity</span></div></div><span class="button store-add">Add to Chrome</span></div><div class="store-preview"><div><p class="preview-label">AI Translator for Chrome</p><strong>Translation, right where you read.</strong></div>${key('Ctrl', 'store-key')}</div><div class="store-dialog"><h3>Add AI Translator?</h3><p>Confirm installation in Chrome.</p><div class="dialog-actions"><span class="store-cancel">Cancel</span><span class="button store-confirm">Add extension</span></div></div><div class="store-installed"><span class="installed-check">✓</span><div><strong>AI Translator added to Chrome</strong><p>Next, connect your Gemini key.</p></div></div>${cursor}`, 'chromewebstore.google.com', 'store-browser')}<div class="install-footer"><span>Find AI Translator in the Chrome Web Store.</span><span>Install once. Make it yours.</span></div>`,
    css: `#s14 .stage{justify-content:flex-start;padding-top:144px}#s14 h1{font-size:97px}#s14 .store-browser{margin-top:7px}#s14 .store-browser .page-content{padding:27px 42px 34px;min-height:438px}#s14 .store-nav{display:flex;align-items:center;justify-content:space-between;padding-bottom:19px;border-bottom:1px solid #e1e1e7;font-size:25px}#s14 .store-nav strong{font-size:29px;font-weight:550;letter-spacing:-.7px}#s14 .store-nav>span{color:#0068c9;font-weight:550}#s14 .store-listing{display:flex;align-items:center;justify-content:space-between;padding-top:27px}#s14 .store-product{display:flex;align-items:center;gap:26px}#s14 .store-product .app-icon{width:105px;height:105px}#s14 .store-product h2{font-size:43px;letter-spacing:-1.5px}#s14 .store-product p{font-size:25px;margin-top:8px;color:#55555f}#s14 .store-category{display:inline-block;font-size:21px;margin-top:12px;color:#6e6e73}#s14 .store-add{border-radius:99px;font-size:26px;padding:17px 30px;min-width:235px;text-align:center;margin-right:12px}#s14 .store-preview{display:flex;align-items:center;justify-content:space-between;margin-top:28px;background:#f1eef7;border:1px solid #e5dfef;border-radius:20px;padding:25px 44px;height:156px}#s14 .preview-label{font-size:22px;color:#694196;margin-bottom:14px;font-weight:600}#s14 .store-preview strong{font-size:36px;letter-spacing:-.9px}#s14 .store-key{width:130px;height:111px;border-radius:19px;padding:16px 20px;border-bottom-width:6px;box-shadow:0 14px 22px #3321441a}#s14 .store-key span{font-size:40px}#s14 .store-key small{font-size:16px;color:#63636b}#s14 .store-dialog{position:absolute;right:54px;top:230px;width:570px;padding:26px 30px;background:#fff;border:2px solid #d8d8df;border-radius:19px;box-shadow:0 18px 48px #2321392b;z-index:3}#s14 .store-dialog h3{font-size:28px;margin:0 0 12px;font-weight:650;letter-spacing:-.5px}#s14 .store-dialog p{font-size:23px;color:#55555f}#s14 .dialog-actions{display:flex;justify-content:flex-end;align-items:center;gap:22px;margin-top:24px}#s14 .store-cancel{font-size:22px;color:#0068c9;padding:11px 17px}#s14 .store-confirm{font-size:23px;border-radius:99px;padding:12px 24px}#s14 .store-installed{position:absolute;left:84px;top:281px;display:flex;align-items:center;gap:24px}#s14 .installed-check{display:flex;align-items:center;justify-content:center;width:67px;height:67px;background:#e8f4eb;border-radius:50%;font-size:38px;color:#287b53}#s14 .store-installed strong{font-size:32px;letter-spacing:-.6px}#s14 .store-installed p{font-size:25px;color:#6e6e73;margin-top:10px}#s14 .cursor{right:122px;top:161px}#s14 .install-footer{display:flex;justify-content:space-between;font-size:25px;color:#6e6e73;margin-top:36px}`,
    motion: `tl.fromTo(q('.store-browser'),{opacity:0,y:30},{opacity:1,y:0,duration:.6,ease:'power3.out'},s+.55);tl.fromTo(q('.store-product'),{opacity:0,x:-25},{opacity:1,x:0,duration:.5,ease:'power3.out'},s+1);tl.fromTo(q('.store-preview'),{opacity:0,y:20},{opacity:1,y:0,duration:.5},s+1.25);tl.fromTo(q('.store-key'),{rotation:6},{rotation:0,duration:.7,ease:'power3.out'},s+1.4);tl.fromTo(q('.cursor'),{opacity:0,x:75,y:70},{opacity:1,x:0,y:0,duration:.65,ease:'power2.inOut'},s+2.7);tl.to(q('.store-add'),{scale:.96,duration:.12,yoyo:true,repeat:1},s+3.55);tl.to(q('.store-preview'),{opacity:0,duration:.2},s+3.8);tl.fromTo(q('.store-dialog'),{opacity:0,y:-12},{opacity:1,y:0,duration:.35,ease:'power3.out'},s+4.05);tl.to(q('.cursor'),{y:212,x:-9,duration:.65,ease:'power2.inOut'},s+4.65);tl.to(q('.store-confirm'),{scale:.96,duration:.12,yoyo:true,repeat:1},s+5.8);tl.to(q('.store-dialog'),{opacity:0,y:-8,duration:.25},s+6.15);tl.to(q('.cursor'),{opacity:0,duration:.25},s+6.15);tl.to(q('.store-add'),{opacity:0,duration:.25},s+6.3);tl.fromTo(q('.store-installed'),{opacity:0,y:15},{opacity:1,y:0,duration:.5,ease:'power3.out'},s+6.4);tl.fromTo(q('.installed-check'),{scale:.8},{scale:1,duration:.5,ease:'back.out(1.4)'},s+6.5);tl.fromTo(q('.install-footer'),{opacity:0},{opacity:1,duration:.5},s+1.1);`,
  },
  {
    id: 's15', theme: 'light',
    html: `<div class="enter">${heading('A quick setup · 2 of 3', 'Connect your Gemini key.')}</div><div class="connect-stage"><div class="key-guide"><p class="setup-step-label">GET YOUR KEY</p><h2>Google AI Studio</h2><p class="studio-address">aistudio.google.com/apikey</p><div class="guide-action"><span class="api-symbol">{ }</span><div><strong>Gemini API key</strong><p>Create or choose your key</p></div></div><span class="button key-action">Create API key</span><p class="guide-foot">The extension includes a step-by-step guide.</p></div><div class="agreement-panel"><p class="setup-step-label">IN EXTENSION SETTINGS</p><h2>Review data sharing</h2><p class="agreement-copy">Google receives your key to check models. When you request a translation, it also receives your selected text and target language.</p><p class="agreement-detail">Your key is saved encrypted on this device.</p><span class="button agree-action">Agree and connect to Google</span><span class="agreement-done"><span class="tick">✓</span> Data agreement saved</span></div></div><p class="corner-note">Free extension. Google API charges may apply.</p>`,
    css: `#s15 .stage{justify-content:flex-start;padding-top:148px}#s15 h1{font-size:90px}#s15 .connect-stage{display:grid;grid-template-columns:690px 1fr;gap:50px;margin-top:16px}#s15 .key-guide,#s15 .agreement-panel{border:2px solid #dcdce3;border-radius:25px;padding:35px 38px;background:#fff;height:477px;position:relative}#s15 .setup-step-label{font-size:21px;letter-spacing:1.5px;color:#6e6e73;margin-bottom:21px;font-weight:650}#s15 h2{font-size:47px;letter-spacing:-1.6px}#s15 .studio-address{font-size:25px;color:#0068c9;margin-top:14px}#s15 .guide-action{display:flex;align-items:center;gap:19px;margin:31px 0 22px}#s15 .api-symbol{width:62px;height:62px;border:2px solid #cecad8;display:flex;align-items:center;justify-content:center;border-radius:14px;font-size:28px;background:#f4f1fa;color:#694196}#s15 .guide-action strong{font-size:30px}#s15 .guide-action p{font-size:24px;color:#6e6e73;margin-top:5px}#s15 .guide-foot{font-size:23px;color:#6e6e73;margin-top:23px;line-height:1.35}#s15 .agreement-copy{font-size:29px;line-height:1.4;margin-top:23px;max-width:755px}#s15 .agreement-detail{font-size:25px;color:#6e6e73;margin-top:16px}#s15 .agree-action{margin-top:26px;font-size:26px;padding:13px 23px}#s15 .agreement-panel{height:540px}#s15 .agreement-done{position:absolute;bottom:22px;left:37px;display:flex;align-items:center;gap:12px;color:#176b2c;font-size:24px}`,
    motion: `tl.fromTo(q('.key-guide'),{opacity:0,x:-45},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+.6);tl.fromTo(q('.guide-action'),{opacity:0,y:15},{opacity:1,y:0,duration:.5},s+1.8);tl.fromTo(q('.agreement-panel'),{opacity:0,x:45},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+d*.35);tl.fromTo(q('.agree-action'),{opacity:0,y:15},{opacity:1,y:0,duration:.45},s+d*.49);tl.to(q('.agree-action'),{scale:.97,duration:.13,yoyo:true,repeat:1},s+d*.62);tl.fromTo(q('.agreement-done'),{opacity:0,y:10},{opacity:1,y:0,duration:.4},s+d*.66);`,
  },
  {
    id: 's16', theme: 'light',
    html: `<div class="enter">${heading('A quick setup · 3 of 3', 'Paste. Choose. Finish.')}</div><div class="finish-stage"><div class="setup-excerpt"><div class="key-row"><p class="setup-label">API key</p><div class="setup-field key-input"><span class="key-placeholder">Paste your API key</span><span class="key-hidden">••••••••••••••••••••••••••••••••••</span><span class="saved-state"><span class="tick">✓</span> Saved</span></div></div><div class="preferences-pair"><div><p class="setup-label">Default language</p><div class="setup-field">German <span>⌄</span></div></div><div><p class="setup-label">Model</p><div class="setup-field">Gemini 3.5 Flash-Lite <span>⌄</span></div></div></div><span class="button finish-button">Finish setup</span></div><div class="ready-stage"><div class="refresh-symbol" data-layout-ignore aria-hidden="true">↻</div><h2>Refresh your<br>open pages.</h2><p class="device-note"><span class="tick">✓</span> Your key stays saved on this device.</p></div></div><p class="corner-note">Free extension. Google API charges may apply.</p>`,
    css: `#s16 .stage{justify-content:flex-start;padding-top:150px}#s16 h1{font-size:99px}#s16 .finish-stage{display:grid;grid-template-columns:1020px 1fr;gap:75px;margin-top:24px;align-items:center}#s16 .setup-excerpt{padding:36px;border:2px solid #dcdce3;border-radius:24px;background:white;box-shadow:0 22px 55px #17121f12}#s16 .setup-label{font-size:27px}#s16 .key-input{position:relative;height:77px;padding:21px 22px;background:#fafafd}#s16 .key-placeholder{font-size:27px;color:#8a8a94}#s16 .key-hidden{position:absolute;left:23px;top:20px;font-size:28px;letter-spacing:1px}#s16 .saved-state{position:absolute;right:20px;top:24px;font-size:22px;color:#176b2c;display:flex;gap:8px}#s16 .preferences-pair{display:grid;grid-template-columns:1fr 1.35fr;gap:27px;margin:32px 0}#s16 .preferences-pair .setup-field{font-size:26px;display:flex;justify-content:space-between;gap:17px;padding:20px}#s16 .finish-button{font-size:28px;padding:14px 27px}#s16 .ready-stage{padding-left:5px}#s16 .refresh-symbol{font-size:120px;line-height:1;color:#0068c9;font-weight:500;width:125px;height:120px;text-align:center;margin-bottom:22px}#s16 .ready-stage h2{font-size:53px;line-height:1.15;letter-spacing:-1.9px}#s16 .device-note{max-width:365px;font-size:27px;color:#6e6e73;line-height:1.4;margin-top:26px;position:relative;padding-left:31px}#s16 .device-note .tick{position:absolute;left:0}`,
    motion: `tl.fromTo(q('.setup-excerpt'),{opacity:0,y:28},{opacity:1,y:0,duration:.6},s+.55);tl.fromTo(q('.key-hidden'),{opacity:0},{opacity:1,duration:.05},s+1.5);tl.to(q('.key-placeholder'),{opacity:0,duration:.05},s+1.5);tl.fromTo(q('.saved-state'),{opacity:0,y:4},{opacity:1,y:0,duration:.35},s+1.7);tl.fromTo(q('.preferences-pair'),{opacity:0,y:18},{opacity:1,y:0,duration:.5},s+d*.24);tl.fromTo(q('.finish-button'),{opacity:0,y:10},{opacity:1,y:0,duration:.4},s+d*.36);tl.to(q('.finish-button'),{scale:.96,duration:.13,yoyo:true,repeat:1},s+d*.44);tl.fromTo(q('.ready-stage'),{opacity:0,x:40},{opacity:1,x:0,duration:.65,ease:'power3.out'},s+d*.48);tl.fromTo(q('.refresh-symbol'),{rotation:-90},{rotation:0,duration:.75,ease:'power2.out'},s+d*.51);tl.fromTo(q('.device-note'),{opacity:0,y:12},{opacity:1,y:0,duration:.45},s+d*.64);`,
  },
  {
    id: 's17', theme: 'dark',
    html: `<div class="closing-brand">${logo}<div><p>AI Translator</p><span>for Chrome</span></div></div><div class="closing-hero"><div class="closing-words"><h1><span class="final-select">Select.</span><span class="final-control">Control.</span><span class="final-understand">Understand.</span></h1></div>${key('Ctrl', 'final-key')}</div><div class="endline"><p>Keep going.</p><span>github.com/miroslavkiev/chrome-ai-translate</span></div>`,
    css: `#s17 .stage{padding:126px 150px 102px;justify-content:flex-start}#s17 .closing-brand{display:flex;align-items:center;gap:25px}#s17 .closing-brand .app-icon{width:115px;height:115px}#s17 .closing-brand p{font-size:40px;font-weight:650;letter-spacing:-1px}#s17 .closing-brand span{font-size:27px;color:#bfb2ce;display:block;margin-top:4px}#s17 .closing-hero{display:flex;justify-content:space-between;align-items:center;margin-top:32px}#s17 .closing-words h1{font-size:128px;line-height:1.08;letter-spacing:-6px}#s17 .closing-words h1>span{display:block}#s17 .final-control{color:#a5cdff}#s17 .final-key{width:355px;height:305px;padding:42px 45px;border-radius:42px;margin-right:105px;box-shadow:0 40px 100px #0005,inset 0 0 0 2px #dbdbe0}#s17 .final-key span{font-size:94px}#s17 .final-key small{font-size:30px}#s17 .endline{margin-top:39px;display:flex;justify-content:space-between;align-items:end;border-top:1px solid #594767;padding-top:31px}#s17 .endline p{font-size:46px;letter-spacing:-1px;font-weight:550}#s17 .endline>span{font-size:26px;color:#c5bbd0;padding-bottom:7px}`,
    motion: `tl.fromTo(q('.closing-brand'),{opacity:0,y:22},{opacity:1,y:0,duration:.55,ease:'power3.out'},s+.1);tl.fromTo(q('.final-select'),{opacity:0,x:-55},{opacity:1,x:0,duration:.55,ease:'power3.out'},s+.45);tl.fromTo(q('.final-control'),{opacity:0,x:-55},{opacity:1,x:0,duration:.55,ease:'power3.out'},s+1.1);tl.fromTo(q('.final-key'),{opacity:0,scale:.86,rotation:7,y:30},{opacity:1,scale:1,rotation:0,y:0,duration:.8,ease:'power3.out'},s+1.1);tl.to(q('.final-key'),{y:8,scale:.97,duration:.12,yoyo:true,repeat:1},s+2);tl.fromTo(q('.final-understand'),{opacity:0,x:-55},{opacity:1,x:0,duration:.55,ease:'power3.out'},s+2.2);tl.fromTo(q('.endline'),{opacity:0,y:16},{opacity:1,y:0,duration:.55},s+1.75);tl.to(q('.final-key'),{y:-12,duration:d*.3,ease:'sine.inOut'},s+d*.6);`,
  },
];
